
--VARIABLE DECLARATIONS
DECLARE @ID INT ,@NAME VARCHAR(20);
DECLARE @DATE DATE='2020-02-24'
SET @ID=1;
SET @NAME='%Sa%'

SELECT * FROM HumanResources.Department
WHERE Name LIKE @NAME

DECLARE @TABLENAME VARCHAR(50)
DECLARE @SQLQUERY VARCHAR(MAX)
SET @TABLENAME='DEPARTMENT'
SET @SQLQUERY='SELECT * FORM HumanResources.Department WHERE [DepartmentID]=2'
EXEC(@SQLQUERY)
GO

--PARAMETERIZED QUERY(TABLE NAMES CANNOT BE USED FOR PARAMETERS)
DECLARE @P1 INT;
DECLARE @SQLQUERY NVARCHAR(MAX);
DECLARE @PREP_HANDLARE INT;
SET @P1=1;
SET @SQLQUERY=N'SELECT * FORM HumanResources.Department WHERE [DepartmentID]=2'
EXEC sp_prepare @PREP_HANDLARE output,N'@P1 NVARCHAR(2)',@SQLQUERY
EXEC sp_execute @PREP_HANDLARE,@P1
EXEC sp_unprepare @PREP_HANDLARE
GO

use AdventureWorks2014
go

DECLARE @P1 INT;
DECLARE @SQLQUERY NVARCHAR(MAX);
DECLARE @PREP_HANDLARE INT;
SET @P1=1;
SET @SQLQUERY=N'SELECT * FORM HumanResources.Department WHERE [DepartmentID]=2'
EXEC sp_prepexec @PREP_HANDLARE output,N'@P1 NVARCHAR(2)',@SQLQUERY,@P1
EXEC sp_unprepare @PREP_HANDLARE
GO


DECLARE @P1 NVARCHAR(MAX);
DECLARE @SQLQUERY NVARCHAR(MAX);
DECLARE @PREP_HANDLARE INT;
SET @P1='Department';
SET @SQLQUERY=N'SELECT * FORM HumanResources.@P1'
EXEC sp_prepexec @PREP_HANDLARE output,N'@P1 NVARCHAR(2)',@SQLQUERY,@P1
EXEC sp_unprepare @PREP_HANDLARE
GO


DECLARE @USERINPUT INT;
DECLARE @Name VARCHAR(50),@GroupName VARCHAR(50);
SET @USERINPUT=1;

--1 SET
SET @Name=(select Name from HumanResources.Department where DepartmentID=@USERINPUT)
SET @GroupName=(select @GroupName from HumanResources.Department where DepartmentID=@USERINPUT)
print @Name
print @GroupName

--ORDER
select @Name as 'NAME',@GroupName AS 'GROUPNAME'

--SELECT 
select @Name=Name,@GroupName=GroupName from HumanResources.Department where DepartmentID=@USERINPUT


DECLARE @NUMBER INT=12
DECLARE @NUMBER1 FLOAT(53)
SET @NUMBER1=CONVERT(FLOAT(53),@NUMBER)
PRINT @NUMBER1
GO

DECLARE @A CHAR(2)='11'
DECLARE @B INT;
SET @B=PARSE(@A AS INT)
PRINT @B

DECLARE @A CHAR(3)='11a'
DECLARE @B INT;
SET @B=PARSE(@A AS INT)
PRINT @B


DECLARE @A CHAR(3)='11a'
DECLARE @B INT;
SET @B=TRY_PARSE(@A AS INT)
PRINT @B


--CONDITIONAL--STATMENT--
DECLARE @DAY_NUMBER INT=10;
IF(@DAY_NUMBER=1)
	SELECT 'SUNDAY'
ELSE
	SELECT 'SOME OTHER DAY'


DECLARE @GENDER CHAR(1)='M'
IF(@GENDER='M')
	BEGIN
		SELECT 'MALE'
	END
ELSE
	BEGIN
		SELECT 'MALE'
	END
GO

DECLARE @ID INT=1;
IF EXISTS(SELECT * FROM HumanResources.Department WHERE DepartmentID=@ID)
BEGIN
	SELECT * FROM HumanResources.Department WHERE DepartmentID=@ID
END
ELSE
BEGIN
	RAISERROR('RECORD NOT EXIST',0,0)
	RAISERROR('RECORD NOT EXISTS',18,0);
END
GO